### ISSUE TITLE
Data Model: Timeline Component

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#150]
**What needs to be research?**
Research and define data model for the timeline content and what possible solutions to intake that data from outside the component. This means: 

- [x] What data does your page need? 
- [x] What data does your page/section output?
- [x] How is data on the form processed?

**What are the deliverables?**
- [x] Quick write up here about how the page will consume that data & what happens if that data changes?
- [x] Create a wiki page titled: Data Model: Timeline Component

**Comment by jal040** [comment]
The data model for the timeline content is formatted into an array. 

The main title of the sections for the timeline content have the following properties: title (string), checkmark (boolean), itemExpand (boolean), dot (boolean), and children (array). 

The children of each section determines the content for that section. The children have the following properties: title (string), checkmark (boolean), and children (array). 

For the main section titles, the itemExpand boolean is so that the user can expand that section. The dot is for the blue dot on the left of each title. The checkmark boolean is always false for the title.

For the children, the very last children of the content (meaning that that item has an empty array for the children property) is the to do items for the timeline. The checkmark boolean is always true for the last children.

**Comment by khoadnguyen** [comment]
Great, thank you for documenting the wiki page as well! 👍
