### ISSUE TITLE
Charts: Page creation

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#213]
**Describe the feature briefly:**
Once your wireframes are approved and finalized (https://github.com/SoftStackFactory/reboot/issues/211), we'll need to actually create the pages and content. You'll be responsible for the page creation, layout, and styling.  
 
**What needs to be done?**
- [x] Create a new chart history main page based on the approved wireframes
- [x] Create a new chart history detail page based on the approved wireframes

**Where does this appear?**
Charts section

**Comment by brettwray** [comment]
@khoadnguyen I think that the results page would be best included on the resources page as we discussed in class on Monday. Rather than a separate page that gives the results, including the chart on the resources page consolidates the amount of pages needed and makes the page more impactful.

History main and History Detail should be wrapped up as well, the history page now contains a detailed chart and table that will allow the user to visualize their self-assessment history.

**Comment by khoadnguyen** [comment]
@brettwray Took out the results page requirement, this looks like it's pretty much wrapped up.
